-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 23:06:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel_user` ENUM("1", "2") NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`user_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `quantidade` INT NOT NULL,
  `category_category_id` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  CONSTRAINT `fk_produto_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produto_category1_idx` ON `mydb`.`produto` (`category_category_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `cep` VARCHAR(7) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_endereco_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_compra_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_compra_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_compra_produto` (
  `user_id` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  `data_compra` DATE NOT NULL,
  `quantidade_compra` INT NOT NULL,
  `user_cpf` VARCHAR(11) NULL,
  PRIMARY KEY (`user_id`, `produto_idproduto`),
  CONSTRAINT `fk_user_has_produto_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_user_has_produto_produto1_idx` ON `mydb`.`user_compra_produto` (`produto_idproduto` ASC) VISIBLE;

CREATE INDEX `fk_user_has_produto_user_idx` ON `mydb`.`user_compra_produto` (`user_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `user_cpf_UNIQUE` ON `mydb`.`user_compra_produto` (`user_cpf` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM("debito", "credito", "boleto") NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cvv` VARCHAR(3) NOT NULL,
  `vencimento` DATE NOT NULL,
  `titular` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idpagamento`),
  CONSTRAINT `fk_pagamento_user_compra_produto1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_compra_produto` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pagamento_user_compra_produto1_idx` ON `mydb`.`pagamento` (`user_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`category` (`category_id`, `name`) VALUES (1, 'Calçados');
INSERT INTO `mydb`.`category` (`category_id`, `name`) VALUES (2, 'Roupas');
INSERT INTO `mydb`.`category` (`category_id`, `name`) VALUES (DEFAULT, 'Higiene');
INSERT INTO `mydb`.`category` (`category_id`, `name`) VALUES (DEFAULT, 'Brinquedos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`produto`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`produto` (`idproduto`, `descricao`, `preco`, `quantidade`, `category_category_id`) VALUES (1, 'Camisa  Floral', 30,00, 5, 2);

COMMIT;

